services:
  main:
    build: .
    container_name: lessrss
    ports:
      - 5000:5000
    volumes:
      - data:/data
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SQLALCHEMY_URL=${SQLALCHEMY_URL}
    develop:
      watch:
        - action: sync
          path: ./src
          target: /src
          ignore:
            - ./src/app/__pycache__/
            - ./src/.venv/
    restart: always
volumes:
  data:
